/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string = string> extends Record<string, unknown> {
      StaticRoutes: `/` | `/(provider)` | `/(provider)/earnings` | `/(provider)/jobs` | `/(provider)/profile` | `/(provider)\profile` | `/(provider)\schedule` | `/(tabs)` | `/(tabs)/bookings` | `/(tabs)/cleaners` | `/(tabs)/home` | `/(tabs)/profile` | `/(tabs)\_layout` | `/(tabs)\home` | `/..\.expo\app\` | `/..\.expo\app\(provider)\_layout` | `/..\.expo\app\(provider)\earnings` | `/..\.expo\app\(provider)\jobs` | `/..\.expo\app\(provider)\profile` | `/..\.expo\app\(provider)\schedule` | `/..\.expo\app\(tabs)\_layout` | `/..\.expo\app\(tabs)\bookings` | `/..\.expo\app\(tabs)\cleaners` | `/..\.expo\app\(tabs)\home` | `/..\.expo\app\(tabs)\profile` | `/..\.expo\app\+html` | `/..\.expo\app\_layout` | `/..\.expo\app\admin` | `/..\.expo\app\auth` | `/..\.expo\app\booking` | `/..\.expo\app\cleaner\[id]` | `/..\.expo\app\client-setup` | `/..\.expo\app\install-prompt` | `/..\.expo\app\join` | `/..\.expo\app\legal` | `/..\.expo\app\my-services` | `/..\.expo\app\onboarding` | `/..\.expo\app\payout` | `/..\.expo\app\provider` | `/..\.expo\app\providers` | `/..\.expo\app\request` | `/..\.expo\app\review` | `/..\.expo\app\roadside` | `/..\.expo\app\services` | `/..\.expo\app\verify-email` | `/..\.expo\components\AvailabilityGrid` | `/..\.expo\components\Avatar` | `/..\.expo\components\Chat` | `/..\.expo\components\Logo` | `/..\.expo\components\PartsPanel` | `/..\.expo\components\PhoneVerify` | `/..\.expo\components\Picker` | `/..\.expo\components\ProposeTime` | `/..\.expo\components\QuotePanel` | `/..\.expo\components\ServiceQuestions` | `/..\.expo\constants\malta` | `/..\.expo\constants\theme` | `/..\.expo\constants\trades` | `/..\.expo\context\AppContext` | `/..\.expo\lib\availability` | `/..\.expo\lib\location` | `/..\.expo\lib\moderation` | `/..\.expo\lib\notify` | `/..\.expo\lib\services` | `/..\.expo\lib\supabase` | `/..\.expo\supabase\functions\send-notification\` | `/..\.expo\supabase\functions\verify-phone\` | `/..\components\AvailabilityGrid` | `/..\components\Picker` | `/..\components\QuotePanel` | `/..\components\ServiceQuestions` | `/..\lib\availability` | `/..\lib\location` | `/..\lib\moderation` | `/_sitemap` | `/admin` | `/auth` | `/booking` | `/bookings` | `/cleaner\[id]` | `/cleaners` | `/client-setup` | `/earnings` | `/home` | `/install-prompt` | `/jobs` | `/join` | `/legal` | `/my-services` | `/onboarding` | `/payout` | `/profile` | `/provider` | `/providers` | `/request` | `/review` | `/roadside` | `/services` | `/verify-email`;
      DynamicRoutes: `/cleaner/${Router.SingleRoutePart<T>}`;
      DynamicRouteTemplate: `/cleaner/[id]`;
    }
  }
}
